[server]
port = 8501
address = "localhost"

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true

[runner]
fastReruns = true

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
